### ISSUE TITLE
运行run.py报错

### ISSUE THREAD

**Issue by kangleblue** [yanbo92/iOS-perf#11]
D:\iOS-perf-master>python3 run.py --udid=38022be6377c4b10a6dfcb2d74a04832199230f2 --bundleid=com.pgdl
Parameters list:
udid 38022be6377c4b10a6dfcb2d74a04832199230f2
bundleid com.pgdl
grafana_host localhost
mysql_host localhost
grafana_port 30000
mysql_port 33306
grafana_username admin
mysql_username root
grafana_password admin
mysql_password admin
mysql_db iOSPerformance
runid
export 0
Error Info: (1050, "Table 'TEMP' already exists")
Maybe this database dont need initializing, just ignore the error
Traceback (most recent call last):
  File "run.py", line 97, in start_test
    pid = t.app_start(app_bundle_id)
  File "D:\Python\Python38\lib\site-packages\tidevice\_device.py", line 653, in app_start
    instruments = self.connect_instruments()
  File "D:\Python\Python38\lib\site-packages\tidevice\_device.py", line 781, in connect_instruments
    conn = self.start_service(LockdownService.InstrumentsRemoteServer)
  File "D:\Python\Python38\lib\site-packages\tidevice\_device.py", line 448, in start_service
    return self._unsafe_start_service(name)
  File "D:\Python\Python38\lib\site-packages\tidevice\_device.py", line 477, in _unsafe_start_service
    conn = self.create_inner_connection(data['Port'], _ssl=_ssl)
  File "D:\Python\Python38\lib\site-packages\tidevice\_device.py", line 288, in create_inner_connection
    self._usbmux._check(data)
  File "D:\Python\Python38\lib\site-packages\tidevice\_usbmux.py", line 94, in _check
    raise MuxReplyError(data['Number'])
tidevice.exceptions.MuxReplyError: UsbmuxReplyCode.ConnectionRefused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 230, in <module>
    start_test()
  File "run.py", line 99, in start_test
    pid = get_pid(app_bundle_id)
  File "run.py", line 80, in get_pid
    app_infos = list(t.instruments.app_list())
  File "D:\Python\Python38\lib\site-packages\tidevice\_device.py", line 789, in instruments
    return self.connect_instruments()
  File "D:\Python\Python38\lib\site-packages\tidevice\_device.py", line 781, in connect_instruments
    conn = self.start_service(LockdownService.InstrumentsRemoteServer)
  File "D:\Python\Python38\lib\site-packages\tidevice\_device.py", line 448, in start_service
    return self._unsafe_start_service(name)
  File "D:\Python\Python38\lib\site-packages\tidevice\_device.py", line 477, in _unsafe_start_service
    conn = self.create_inner_connection(data['Port'], _ssl=_ssl)
  File "D:\Python\Python38\lib\site-packages\tidevice\_device.py", line 288, in create_inner_connection
    self._usbmux._check(data)
  File "D:\Python\Python38\lib\site-packages\tidevice\_usbmux.py", line 94, in _check
    raise MuxReplyError(data['Number'])
tidevice.exceptions.MuxReplyError: UsbmuxReplyCode.ConnectionRefused

**Comment by kangleblue** [comment]
@yanbo92 大佬帮忙看下
