### ISSUE TITLE
运行时报错，求助

### ISSUE THREAD

**Issue by iceZT** [yanbo92/iOS-perf#8]
在运行时报错，错误如下
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.1\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/xingnengceshi/iOS-perf-master/run.py", line 213, in <module>
    for d in um.device_list():
  File "C:\Users\a\AppData\Local\Programs\Python\Python310\lib\site-packages\tidevice\_usbmux.py", line 76, in device_list
    data = self.send_recv(payload)
  File "C:\Users\a\AppData\Local\Programs\Python\Python310\lib\site-packages\tidevice\_usbmux.py", line 47, in send_recv
    with self.create_connection() as s:
  File "C:\Users\a\AppData\Local\Programs\Python\Python310\lib\site-packages\tidevice\_usbmux.py", line 44, in create_connection
    return PlistSocket(self.__address, self._next_tag())
  File "C:\Users\a\AppData\Local\Programs\Python\Python310\lib\site-packages\tidevice\_safe_socket.py", line 97, in __init__
    super().__init__(addr)
  File "C:\Users\a\AppData\Local\Programs\Python\Python310\lib\site-packages\tidevice\_safe_socket.py", line 48, in __init__
    self._sock.connect(addr)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

技术不精，研究了一阵没什么头绪，不知道如何解决

**Comment by yanbo92** [comment]
装个itunes或者爱思助手再试试

**Comment by chenLynne** [comment]
大佬，帮忙看下运行时报错，错误如下：
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/datasources (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbb1d9bbe80>: Failed to establish a new connection: [Errno 61] Connection refused'))

**Comment by chenLynne** [comment]
运行后，解析出来的数据是这样的：
grafana_host localhost
mysql_host 127.0.0.1
grafana_port 3000
mysql_port 3306
grafana_username admin
mysql_username root
grafana_password admin
mysql_password admin
mysql_db iOSPerformance
runid 
export 0

**Comment by chenLynne** [comment]
> 大佬，帮忙看看下运行时报错，错误如下： requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/datasources (Caused by NewConnectionError('<urllib3 .connection.HTTPConnection 对象位于 0x7fbb1d9bbe80>：无法建立新连接：[Errno 61] 连接被拒绝'))

@yanbo92 大佬 help~
